languageCode = "en"
languageName = "English"
weight = 1
title = "The Celestials"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Krysty"
  image = "img/avatar.png"
  headline = "author info"
  bio = "CelestEX(Celestial Experimental Unit)-001"
   links = [
    # { link = "" },
    # { github = "https://github.com/Krysty218" },
     # { x-twitter = "https://twitter.com/burufugu" }
   ]